### ISSUE TITLE
Feat: add fixtures to share the same database with all the team

### ISSUE THREAD

**Issue by oladhari** [oladhari/e-commerce#14]
**checklist:**

- [x] create categories 
- [x] create items
- [x] share media files with all the team
- [x] create django fixtures file

**Comment by oladhari** [comment]
load fixtures in new folder did not work, getting this error:
```console
Traceback (most recent call last):                                                                                                                                                                         
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute                                                                                    
    return self.cursor.execute(sql, params)                                                                                                                                                                
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)                                                                                                                                             [0/908]
sqlite3.IntegrityError: UNIQUE constraint failed: market_userprofile.user_id                         
                         
The above exception was the direct cause of the following exception:
                                                                                                     
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>                                                           
    execute_from_command_line(sys.argv)                                                              
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()                          
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)                                                               
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)                                                           
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)                                                                   
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 190, in load_label
    obj.save(using=self.using)                                                                       
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)                             
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(         
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/models/base.py", line 845, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/models/base.py", line 899, in _do_update
    return filtered._update(values) > 0
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/oladhari/.virtualenvs/ecom/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: Problem installing fixture '/home/oladhari/e-commerce/e-commerce/home/fixtures/fixtures.yaml': Could not load market.UserProfile(pk=1): UNIQUE constraint failed: market_us
erprofile.user_id   
```

**Comment by Farid212** [comment]
what does that mean?

**Comment by oladhari** [comment]
> what does that mean?

it does not run the fixtures in a new install
